version: "3.8"

services:
  pihole:
    container_name: pihole
    hostname: "rpi-pihole"
    image: pihole/pihole:2021.10.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${PIHOLE_INTERFACE_PASSWORD}
    volumes:
      - /etc/pihole:/etc/pihole
      - /etc/dnsmasq.d:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
