version: "3.8"

services:
  pihole:
    container_name: pihole
    hostname: "rpi-pihole"
    image: pihole/pihole:2021.10.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - DNS1=${DNS1}
      - DNS2=${DNS2}
      - ServerIP=${ServerIP}
      - IPv6=false
      - TEMPERATUREUNIT=c
      - WEBUIBOXEDLAYOUT=boxed
      - WEBTHEME=default-dark
      - FTLCONF_REPLY_ADDR4=${FTLCONF_REPLY_ADDR4}
      - FTLCONF_MAXDBDAYS=14
    volumes:
      - /etc/pihole:/etc/pihole
      - /etc/dnsmasq.d:/etc/dnsmasq.d/
      - $HOME/data/pihole/adlists.list:/etc/pihole/adlists.list
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
