version: "3.8"

services:
  pihole:
    container_name: pihole
    hostname: "rpi-pihole"
    image: pihole/pihole:2024.01.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - FTLCONF_LOCAL_IPV4=192.168.178.123
      - PIHOLE_DNS_=1.1.1.1;1.0.0.1
      - IPv6=false
      - TEMPERATUREUNIT=c
      - WEBUIBOXEDLAYOUT=boxed
      - QUERY_LOGGING=true
      - WEBTHEME=default-dark
      - FTLCONF_MAXDBDAYS=14
    volumes:
      - /etc/pihole:/etc/pihole
      - /etc/dnsmasq.d:/etc/dnsmasq.d/
      - $HOME/data/pihole/adlists.list:/etc/pihole/adlists.list
      - $HOME/data/pihole/custom.list:/etc/pihole/custom.list
      - $HOME/data/pihole/regex.list:/etc/pihole/regex.list
      - $HOME/data/pihole/whitelist.txt:/etc/pihole/whitelist.txt
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN
    restart: unless-stopped
