version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    # user: "1000" # needs to be `id -u` // alternatively chown the grafana/data dir to 472:472
    user: "1000"
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - type: volume
        source: data
        target: /var/lib/grafana
        volume:
          nocopy: true
      - type: volume
        source: provisioning
        target: /etc/grafana/provisioning
        volume:
          nocopy: true
      - $HOME/docker/config/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

volumes:
  data:
    driver_opts:
      type: "nfs4"
      o: "addr=${IP_ADDRESS},rw,nolock"
      device: ":${SHARE_PATH}/grafana/data"
  provisioning:
    driver_opts:
      type: "nfs4"
      o: "addr=${IP_ADDRESS},rw,nolock"
      device: ":${SHARE_PATH}/grafana/provisioning"
