version: "3.8"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    environment:
      TZ: "Europe/Berlin" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true

volumes:
  data:
    driver_opts:
      type: "nfs4"
      o: "addr=${IP_ADDRESS},rw,nolock"
      device: ":${SHARE_PATH}/portainer/data"
