version: "3.2"

networks:
  metrics:
    external: false

services:
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influxdb
    restart: always
    networks: [metrics]
    ports:
      - "8086:8086"
    volumes:
      - type: volume
        source: data
        target: /var/lib/influxdb
        volume:
          nocopy: true
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./config/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  telegraf:
    image: arm32v7/telegraf:latest
    container_name: telegraf
    networks: [metrics]
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

  chronograf:
    container_name: chronograf
    restart: always
    image: arm32v7/chronograf:latest
    ports:
      - "127.0.0.1:8888:8888"
    depends_on:
      - influxdb
    networks: [metrics]
    environment:
      - INFLUXDB_URL=http://influxdb:8086 # needs to match container_name
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

volumes:
  data:
    driver_opts:
      type: "nfs4"
      o: "addr=${IP_ADDRESS},rw,nolock"
      device: ":${SHARE_PATH}/influxdb/data"
